### ISSUE TITLE
Import Recharts and build graph & legend UI component

### ISSUE THREAD

**Issue by euanmillar** [opencrvs/opencrvs-core#1578]
Update the existing chart component if not too old?

Include the interactive legend

**Comment by jpye-finch** [comment]
As a user, I want to see a graph showing regstrations rates overtime, so that I can easily view our performance

Acceptance criteria
GIVEN I am on the registration rates detialed view
WHEN overtime is selected
THEN show a graph of the rates for my selected time period

GIVEN I am on the registration rates detailed view
WHEN on page load
THEN set the legend to the latest month

GIVEN I hover over the graph
THEN highlight the month I am on

GIVEN I hover over the graph line
THEN highlight the figure for the line I am on

Design
(Link to figma)

- [ ] Import recharts
- [ ] Build graph UI
- [ ] Build interactive legend UI
