### ISSUE TITLE
Build table UI component

### ISSUE THREAD

**Issue by euanmillar** [opencrvs/opencrvs-core#1579]

**Comment by jpye-finch** [comment]
@euanmillar This is an example of a subtask that should and could be written a user story. 

my first comment :)

**Comment by jpye-finch** [comment]
eg. 

As a user (applies to all), I want to view a table of registration rates for my selected time period, so that i can review our performance

**Acceptance criteria**
GIVEN I am on the Regsitration rates page
WHEN I am viewing the data Overtime
THEN show a table for my selected time period

GIVEN I am on the Regsitration rates page
WHEN I click a column heading
THEN re-order the table

**Design**
(Link to figma)
