### ISSUE TITLE
Build loading view UI

### ISSUE THREAD

**Issue by euanmillar** [opencrvs/opencrvs-core#1581]

**Comment by jpye-finch** [comment]
As a user, I want to see that the page is loading, so that I know something is happening

**Acceptance criteria**
GIVEN I have searched for a location
WHEN loading
THEN show the placeholder loading state for the Ops Dashboard

GIVEN I selected to view Birth or Deaths registration rate in detail
WHEN loading
THEN show the placeholder loading state for the Regsitration rates page

**Design**
(Link to figma)
