### ISSUE TITLE
Record audit

### ISSUE THREAD

**Issue by jpye-finch** [opencrvs/opencrvs-core#1636]
### Problem statement
If any problems or questions arise with a record. A detailed view of the history of what has happened to the record is required.

### Proposed work
- removing case-tracking from expanded work-queue row
- move to a new dedicated page to show the record. 
- clicking on an Action shows a model overlay with detail of the action

### Design
https://www.figma.com/file/HplYu3vGJjAz3u1AmNJ50C/00.OpenCRVS-Specifications?node-id=0%3A1

Table: describes the different statuses and actions
https://www.notion.so/opencrvs/Audit-5ea0204d2b6c40858e772028784db864

### Success criteria
(The criteria that must be met in order to consider this project a success)

### Scope
- Record audit page and model views

### Future work
- hide PII data for search results
- mobile optimisation

**Comment by euanmillar** [comment]
Closing due to lack of information

**Comment by euanmillar** [comment]
Audit from the perspective of a record.  Should be reopened and closely linked in design to user audit perhaps? https://github.com/opencrvs/opencrvs-core/issues/1800

**Comment by SyedaAfrida** [comment]
**Bugs:**

1.In Field agent, there is no tracking ID in audit record page of sent for review. But Tracking ID is available in workqueue.
Should have tracking ID in audit record page of sent for review.
![1](https://user-images.githubusercontent.com/94350336/161708747-1fad0888-bc2c-4e68-b4f0-8a64b25fdbda.png)

2. Updated declaration dialogue not showing correct
![2](https://user-images.githubusercontent.com/94350336/161708967-66924b45-5759-403b-a7f1-0b8242d4f650.png)

Informant, father & mother's NID and Name is mixed up in Update declaration dialogue.

https://user-images.githubusercontent.com/94350336/161709055-4c358b4f-9ae5-460f-8482-e04c59a1ab10.mp4

3.  There is no sync in Registration agent and registrar audit record page.
From a Registration agent, Update a declaration which was rejected previously and Send for Approval. In registrar, the record is found in ready for review ( as expected) but in record audit page the status and history are not updated.
Can have a refresh option in the audit page. So that whenever it is clicked it fetch all the latest status and history.
![3(1)](https://user-images.githubusercontent.com/94350336/161710961-9940a7c2-3674-4a9d-9465-75573dc7bf69.png)

![3(2)](https://user-images.githubusercontent.com/94350336/161710992-5a4a1b16-c934-4303-842c-fb0ed0178fe0.png)

4.In registrar in progress tab, update button is missing in record audit page

https://user-images.githubusercontent.com/94350336/161711411-d6101fbc-6b21-4b57-9d50-08704beffe67.mp4

5. From Registration agent, if clicked download from sent for approval tab, then when logged in as Registrar, in audit record page there is no review button.

https://user-images.githubusercontent.com/94350336/161711748-7776aad3-51c1-4115-a6ff-bf57fbcb3102.mp4

6. Should have space between the word "legal guardian" in informant name
![7](https://user-images.githubusercontent.com/94350336/161711968-5e4815a9-fb8a-4237-a409-ac8f5e953520.png)

7. In history of audit record, Certified and reinstate not showing in Action
8.  In sent for updates, action for rejected application should be sent for updates. Currently showing rejected. And reason not showing in dialogue.
![9](https://user-images.githubusercontent.com/94350336/161712432-09b0443a-7841-4168-8653-4d05cdb48493.png)

10. Space between Tracking Id
11. Avoid '_' in son_in_law/ daughter_in_law
![10_11](https://user-images.githubusercontent.com/94350336/161712347-401f8f3a-4d3f-4c88-9809-f50f15e42ebb.png)

12. all the button in mobile view should be below the informant details.
![9](https://user-images.githubusercontent.com/94350336/161712697-52e9e998-4469-4899-824e-e6c3a66eec22.png)

**Concern:**
1. For registration agent, in sent for Approval there is no download icon in work queue. Previously, there was no download icon in workqueue. but to fetch history data, Currently there is a download icon in sent for approval. 
So there is incosistency in workqueue and audit record page

**Comment by anny320** [comment]
closed
