### ISSUE TITLE
As a user I want to see a list of actions performed on a record so I can review the record history

### ISSUE THREAD

**Issue by jpye-finch** [opencrvs/opencrvs-core#2425]
### Description
- adds record history table to Record Audit page
- can see the action, date, whom, and where
- [List of audit Actions](https://www.notion.so/opencrvs/Audit-5ea0204d2b6c40858e772028784db864)

### Acceptance criteria

GIVEN I am on the record Audit page
THEN sow the list of Actions for that record

GIVEN I am on the record Audit page
THEN show the list of Actions oldest first

GIVEN I am on the record Audit page
THEN show the action, date, time, user, type of user, and location

GIVEN I am on the record Audit page
WHEN a user clicks on the user name or location
THEN link to that User Audit Page or that office Team Page

### Design
https://www.figma.com/file/HplYu3vGJjAz3u1AmNJ50C/00.OpenCRVS-Specifications?node-id=1810%3A33851

### Dev-tasks
- [x]  Use the new TableView component created in Correct Record - 2
- [x] List the actions as links, date, user with avatar, user type and location. - 2

**Comment by euanmillar** [comment]
Blocked by 2544

**Comment by SyedaAfrida** [comment]
1.There is no sync in Registration agent and registrar audit record page.
From a Registration agent, Update a declaration which was rejected previously and Send for Approval. In registrar, the record is found in ready for review ( as expected) but in record audit page the status and history are not updated.
Can have a refresh option in the audit page. So that whenever it is clicked it fetch all the latest status and history.
![3(1)](https://user-images.githubusercontent.com/94350336/161710961-9940a7c2-3674-4a9d-9465-75573dc7bf69.png)

![3(2)](https://user-images.githubusercontent.com/94350336/161710992-5a4a1b16-c934-4303-842c-fb0ed0178fe0.png)

2. In history of audit record, Certified and reinstate not showing in Action
![8](https://user-images.githubusercontent.com/94350336/161730826-3c976704-a530-43db-b7ef-8d7218520da5.png)

3.  In sent for updates, action for rejected application should be sent for updates. Currently showing rejected. And reason not showing in dialogue.
![9](https://user-images.githubusercontent.com/94350336/161712432-09b0443a-7841-4168-8653-4d05cdb48493.png)

**Comment by euanmillar** [comment]
This will be resolved by the COnflicts work @SyedaAfrida @anny320

**Comment by SyedaAfrida** [comment]
@anny320 Please block this ticket. QA can't test this ticket as Conflict is not deployed to QA

**Comment by anny320** [comment]
awaiting retest once conflicts is loaded to QA

**Comment by SyedaAfrida** [comment]
@anny320 all the 3 bugs mentioned in the comments are fixed
![1](https://user-images.githubusercontent.com/94350336/175237088-5d3fddbd-33a1-4fae-90a6-ee495c7012f4.png)
![certified passed](https://user-images.githubusercontent.com/94350336/175237108-306f3f9d-61d6-4e69-8f48-159703d29d44.png)
![3](https://user-images.githubusercontent.com/94350336/175237137-863b62f1-1d51-46cf-af2e-05dc9f13484e.png)

**Comment by anny320** [comment]
completed
