### ISSUE TITLE
Create National Administrative Level = Farajaland 

### ISSUE THREAD

**Issue by jpye-finch** [opencrvs/opencrvs-core#2844]
### Description

- we don't have a performance administrative level for the whole country!!
- this ticket is to add this level.
- the default Performance level  for National Registrar, National System Admin and Performance Managers

### Acceptance criteria

GIVEN
WHEN
THEN

### Dev-tasks

- [ ] Get total metrics fetches all country data. Calculates the total performance statistics and estimations by adding up all locations that have a partOf property like this: "Location/0", ie state.
- [x] In Search microservice, amend responses to status window needs to suport country level requirements.
- [x] Hardcoding country name from an intl message into the location search.

**Comment by euanmillar** [comment]
@anny320 @jpye-finch  I think we will handle this in performance via a calculation of all states rather than creating a national location itself.  National HQ's are often the city registration office in a capital city.  By default National Registrar / Sys Admin users see a calculated national view of performance rather than actually a national location.  It achieves the same result you are after.

**Comment by jpye-finch** [comment]
ok cool. Just need a Farajaland option in the location search.

Please see the other ticket for [creating offices at each Province level ](https://app.zenhub.com/workspaces/opencrvs-core-5afeded64a54b06b54a969b2/issues/opencrvs/opencrvs-core/2845)

**Comment by anny320** [comment]
completed
