### ISSUE TITLE
Save Button doesn't appear after after uploading a profile image 

### ISSUE THREAD

**Issue by azantor64** [opencrvs/opencrvs-core#2850]
**Summary of the bug**
After uploading a profile image in any user , save button doesn't exist in desktop view
But in mobile view a button appears but it's 1/3 visible

**To Reproduce**
Steps to reproduce the behaviour:
1. Log in as any User
2. Click on 'Profile section' > Settings
3. Click on user profile >upload a picture
4. **_Try to Save profile picture in desktop view_**
5. **_Try to save profile picture in mobile view_**

**Expected behaviour**
There should be a button which will be visible & save the profile picture

**Screenshots Desktop view**
![image.png](https://images.zenhubusercontent.com/619f3ae43a0c92533cd6c6db/d3157dfe-75c0-4503-b38b-37b4ca843310)

**Screenshots Mobile view**
![image.png](https://images.zenhubusercontent.com/619f3ae43a0c92533cd6c6db/de4008cb-cfd2-48e8-8a71-14a0b74e5d9e)

**Comment by azantor64** [comment]
@jpye-finch  maybe this issue is related to design.

**Comment by jpye-finch** [comment]
this issue was introduced by me. offsetting ResponsiveModel from the centre of the page. so it sits higher up. Impact i wasn't aware of was the FullPage version of ResponsiveModel that was never specified. Please see design https://www.figma.com/file/HplYu3vGJjAz3u1AmNJ50C/OpenCRVS-Design-Specifications?node-id=4780%3A104181

- quick fix: remove the -80px. 
- ideal fix: match design

**Comment by azantor64** [comment]
This is passed can be closed @anny320 
![image](https://user-images.githubusercontent.com/70468099/170038103-745c38c0-1a58-47d0-b596-4bd91c0b9e77.png)
![image](https://user-images.githubusercontent.com/70468099/170038238-9bdee3f3-d312-40c5-bdcd-13f8c74fee55.png)
