### ISSUE TITLE
system/browser default font shows before OpenCRVS Noto sans

### ISSUE THREAD

**Issue by jpye-finch** [opencrvs/opencrvs-core#2906]
**Describe the bug**
- we get a flash of the system/broswer font before OpenCRVS font loads
- need find way to load in fonts before showing font end....
https://images.zenhubusercontent.com/91778759/4ff93853-0438-4771-8c4c-5ec6c2a2d8ad/fonts.mp4

**To Reproduce**
Steps to reproduce the behaviour:
1. Refresh page

1. Clicking on work-queues after a recent login

**Expected behaviour**
- you instantly see Noto Sans

**Comment by euanmillar** [comment]
@jpye-finch we cant fix this unless the text is a configurable SVG where font is outlined, because the loading of the font takes time that needs a loader.  So we cant load fonts before showing the loader.  A configurable SVG for all countries would be a config headache.  The best thing we can do is change the loader to remove text.  While communicating with the user about what is happening is nice, we can only do it with outlined fonts if text is to be included in the loader

**Comment by euanmillar** [comment]
@jpye-finch I looked into this again.  Best solution is to remove text.  The problem is how the site loads.  It waits for all offline content to load before showing the page.  To make this work we would have to load translations offline first, then show the loader, then load the rest of the content.  Its a lot of work for something quite small at this stage.  Maybe we could improve in v2 or maybe use illustrations somehow?

**Comment by anny320** [comment]
completed
