### ISSUE TITLE
Certificate config Semi-bold fonts

### ISSUE THREAD

**Issue by jpye-finch** [opencrvs/opencrvs-core#3026]
**Describe the bug**
- unable to get Semi-bold font styles ot appear
- probably me missing something simple

SVG template (ask me for it. can't seem to add here...?)
![qa-testing-certificatesJPF.svg](https://images.zenhubusercontent.com/5e96badd8bea57051ce92eaf/80364fd5-f1b3-4f81-aefe-9e8dd5165a57)

Preview
![image.png](https://images.zenhubusercontent.com/5e96badd8bea57051ce92eaf/fd33bcf4-69d7-4824-8b88-03b11ae069cc)

**Comment by euanmillar** [comment]
@jpye-finch is this resolved now after Tahmids work?

**Comment by jpye-finch** [comment]
@euanmillar don't think so. The font weight is still 400. 
<img width="1100" alt="image" src="https://user-images.githubusercontent.com/46478402/174759833-df505341-7a0f-4112-aa0e-801014f570de.png">

**Comment by euanmillar** [comment]
@tahmidrahman-dsi could you please discuss this with @jpye-finch ?

**Comment by tahmidrahman-dsi** [comment]
Sure @euanmillar , will do

**Comment by tahmidrahman-dsi** [comment]
@jpye-finch I think svg font family has no effect to pdf font I think. While generating PDF. The current implementation always uses noto sans regular

**Comment by euanmillar** [comment]
We think in the future, that we will have a font upload file in the cert config set to the desired weight for all dynamic text.  We will convert that to base64 and save in the database.  This will be downloaded and saved into IndexedDB along with the other application config variables.  Then the font will be loaded into the vfs dynamically from IndexedDB so that it woks offline.  It seems to be the only way to do this properly.  1 customisable font for all dynamic text.  The rest of the fonts on the cert must be outlines

**Comment by euanmillar** [comment]
So essentially we need a Certificate Config v2 story that has a font upload feature so that all certificate fonts can be customised including weights
