### ISSUE TITLE
Sometimes system crash when try to declare a birth/ death declaration

### ISSUE THREAD

**Issue by SyedaAfrida** [opencrvs/opencrvs-core#3084]
**Bug description:**
Sometimes system crash when try to declare a birth/ death declaration. This bug do not appear always.

**Steps to reproduce:**
1. Login as field agent
2. Declare a birth/ death event
3. Go to "Who is the main point of contact for this declaration? ""
4. Enter phone number> Continue

**Actual result:**
Sometimes system crash

**Expected result:**
should be able to continue to next page always

**Screenshot:**
![new system crash.png](https://images.zenhubusercontent.com/61920d086b30792f101fb9a3/d19d8e88-0e5a-4341-a2d3-baf1ea58daa3)

**Tested on:**
https://login.farajaland-qa.opencrvs.org/

**Comment by euanmillar** [comment]
Cannot replicate

**Comment by euanmillar** [comment]
Cannot replicate

**Comment by anny320** [comment]
closed

**Comment by Fariha-Amin** [comment]
@anny320  When an application is in outbox, if user tries to declare new event, system crashes.

**Recording:**

https://user-images.githubusercontent.com/105624748/173505247-a6497ac1-fc84-4fa6-9308-32c2dd67cab1.mp4

**Comment by anny320** [comment]
issue re-occuring

**Comment by atiqzaman-dsi** [comment]
This issue wont happen again after the following fix:
https://github.com/opencrvs/opencrvs-core/issues/3452

**Comment by Fariha-Amin** [comment]
> @anny320 @Fariha-Amin could you please confirm this? Because this issue wont happen again for the following fix: #3452

System Crash issue is not happening now, but while trying to declare a new event, when there is another application in outbox, then new event declaration process can't be completed, being terminated in midway.
**Note: This problem is not fully consistent**

**steps:**
1. Go on slow 3G 
2. approve/register an event
3. when application is in outbox, try to declare a new event, the declaration process can't becompleted

Recording:

https://user-images.githubusercontent.com/105624748/174236712-e383b0af-6b82-4e32-b80e-d0316e8d87d0.mp4

**Comment by Fariha-Amin** [comment]
@anny320  solved, can be closed 

**Retest Recording:**

https://user-images.githubusercontent.com/105624748/174781059-4c242a91-f839-400a-bd75-0b9bba04446b.mp4
