### ISSUE TITLE
Wrong calculation in Performance "Source of application"

### ISSUE THREAD

**Issue by SyedaAfrida** [opencrvs/opencrvs-core#3133]
**Bug description:**
Wrong calculation in Performance "Source of application". The current calculation is based on only applications that have been registered. Should be based on all applications whether its on ready for review or anything else

**Steps to reproduce:**
1. Login as any user other than field agent
2. Go to Performance

**Actual result:**
The current calculation is based on only applications that have been registered.

**Expected result:**
Should be based on all applications whether its on ready for review or anything else

**Tested on:**
https://login.farajaland-qa.opencrvs.org/

**Comment by euanmillar** [comment]
Need to discuss with @eduffus because in my view this statistic should only count registrations because anything in a workqueue should not be considered as being an item which is guaranteed to be registered.  It could be rejected at any point.  Therefore this statistic will be skewed.  Also this is a lot of work, because if we track an application which is then later rejected, we need to find the specific statistic and remove it.  I think this is fine the way it is.

**Comment by euanmillar** [comment]
According to @eduffus the calculation is correct as this metric is sources of applications that are now registered so we can close this bug
