### ISSUE TITLE
"Certificate issued" field is not being updated in performance page for death certificates

### ISSUE THREAD

**Issue by Fariha-Amin** [opencrvs/opencrvs-core#3251]
**Description:**
"Certificate issued" field is not being updated in performance page for death certificates .

**Steps:**
1.login as registrar
2.print some death certificates
3. login as any user
4. goto performance page
5. select death as event
6. observe "certificates issued" field

**Actual Result:**
"Certificate issued" field is not being updated in performance page for death certificates . For death certificates that are issued, "Certificate issued" field is always  showing "0" .
Expected Result:
"Certificate issued" field should be updated in performance page for issued  death certificates. 

**ScreenShots:**
![c1](https://user-images.githubusercontent.com/105624748/170936074-b6e2da3e-bfde-455e-8db3-57e623ad7f34.PNG)
![c2](https://user-images.githubusercontent.com/105624748/170936086-15d328bc-afa4-4129-b5bd-0effd6212069.PNG)

**Tested on:**
https://login.farajaland-qa.opencrvs.org/

**Desktop:**
OS: Windows 10, Ubuntu
Browser: Chrome

**Comment by euanmillar** [comment]
@rikukissa there is a bug where basically if the fee is zero, then metrics service doesnt track that the certificate is certified.  This happens in the case of all events registered within the target time period. @soumita-dsi  is working on a fix.  Hopefully I can merge it today otherwise I would hold off data generation starting till this fix is deployed to prod.

**Comment by Fariha-Amin** [comment]
@anny320  passed, can be closed

Retest Recording:


https://user-images.githubusercontent.com/105624748/172542658-2be890af-b75d-4964-846a-7c6c3d5f8a3a.mp4

**Comment by anny320** [comment]
completed
