### ISSUE TITLE
In mobile view when offline, texts are overlapping and not aligned

### ISSUE THREAD

**Issue by Fariha-Amin** [opencrvs/opencrvs-core#3328]
**Description:**
In mobile view when offline, texts are overlapping and not aligned 

**Steps:**
1.Login as any user in mobile view
2. go offline
3. goto in progress/ready for review/ready to print/requires update
4. observe the " Reconnect to load declarations" text

**Actual Result:**
**1. In mobile view when offline, texts are overlapping** 
![mobile_view_overlap](https://user-images.githubusercontent.com/105624748/171639723-3affb114-d7b5-413d-8b1c-cb3709798d53.PNG)
![mobile_overlap_2](https://user-images.githubusercontent.com/105624748/171639732-234b47bf-558c-478b-bcf7-62646188c93a.PNG)

2. **The no connection icon and " Reconnect to load declarations" text are not aligned.**
![mobile_unaligned](https://user-images.githubusercontent.com/105624748/171640083-e3f773bf-90b4-455e-89f8-2d85ecf8d815.jpg)

**Expected Result:**
In mobile view when offline, texts should not overlap and icon and text should be aligned

**Tested on:**
https://login.farajaland-qa.opencrvs.org/

**Desktop:**
OS: Windows 10, Ubuntu
Browser: Chrome

**Comment by jpye-finch** [comment]
taking forever to generate a figma link 

heres an image for now ![image.png](https://images.zenhubusercontent.com/5e96badd8bea57051ce92eaf/18114750-d893-4ba1-99fc-debf81797d5f)

**Comment by SyedaAfrida** [comment]
@anny320 this bug is fixed and can be closed
![mob1](https://user-images.githubusercontent.com/94350336/178674210-e5a2e581-56e3-4d89-a318-de0fd9863ddc.png)
![mob2](https://user-images.githubusercontent.com/94350336/178674230-a335d7a8-4347-452c-b631-261edfebc358.png)
![mob3](https://user-images.githubusercontent.com/94350336/178674243-03d81df9-2eef-4022-a7d2-e692324f6b9f.png)

**Comment by anny320** [comment]
completed
