### ISSUE TITLE
Certificate label does not reflect the name of the Registrar who registered the record

### ISSUE THREAD

**Issue by jpye-finch** [opencrvs/opencrvs-core#3352]
**Describe the bug**
- name of the user who is printing the certificate appears on the certificate.
- It should be the Registrar who registered the record

**To Reproduce**
Steps to reproduce the behaviour:
1. Login in as a Registration agent. Felix
2. Download and declaration
3. Click Print
4. Go to preview. The signature shows the Registrar. but the label is the Registration agents name

**Expected behaviour**
It should be the name of the Registrar who registered the record. Whose signature is above.

**Screenshots**
![image.png](https://images.zenhubusercontent.com/5e96badd8bea57051ce92eaf/a4c13742-b622-4672-aefd-f097868fa1d1)

**Comment by euanmillar** [comment]
Currently the signature is always the registrar associated with the logged in user's office and it is returned in the userDetails indexedDB object.  But this isnt going to work because of this bug.  So instead we need to amend the Download function fetch

**Comment by saima-alam** [comment]
@anny320 Certificate label now showing the name of the Registrar who registered the record. This can be closed. 
![image](https://user-images.githubusercontent.com/105625699/173033489-95b58fdd-517c-4b76-814a-3b45df2f251e.png)

There is an issue that the user role is showing who is printing the certificate instead of who registered the record.  I have added a separate bug for the user role issue #3437.
