### ISSUE TITLE
Need valid token for search birth and death records in OpenCRVS

### ISSUE THREAD

**Issue by rajdeep21randhava** [opencrvs/opencrvs-core#3666]
**Describe the bug**

Our inoperability service communicates with OpenCRVS to search birth and death records. We used the following link to get an authentication token.

https://documentation.opencrvs.org/technology/interoperability/authentication-and-authorization

However, we are not able to search using the token genrated using the above document. 

We have used a bearer token from the OpenCRVS application (Got from inspect element of OpenCRVS please find the screenshot as following). If we use the token of the application we got the expected output.

![image](https://user-images.githubusercontent.com/105046784/179942920-908657d7-2bb0-4523-9353-c129271e7eb0.png)
 
**Screenshots**
We are creating Token Using http://auth.localhost:4040/authenticateSystemClient URL with created client_id and client_secret

![image](https://user-images.githubusercontent.com/105046784/179943873-e8c4daac-06dd-4ac6-8e17-63bed5199b7a.png)

**Expected behavior**
We expected to search for birth and death registration records using the above-generated token. (Note: If we use the token of the application we got the expected output.)
![image](https://user-images.githubusercontent.com/105046784/179944571-1f1a8ea2-7a53-43e6-a2c5-249132bbcce3.png)
![image](https://user-images.githubusercontent.com/105046784/179944684-bda4f857-40ba-4da6-aeaa-42c740117151.png)
![image](https://user-images.githubusercontent.com/105046784/179944784-b94d04e9-ba84-4449-b6e9-43beab3ea37d.png)
 
**Desktop (please complete the following information):**
 - OS:Ubuntu 20.04.4 LTS
 - Browser : Chrome
 - Postman 
 
Please let us know if the token which we have created is valid for searching birth and death records. Please suggest if there is some other alternative way. 

Regards,
Rajdeep

**Comment by euanmillar** [comment]
Hi Rajdeep,

First of all, thanks for getting in touch!

Regarding what you are trying to do via Postman and GraphQL ... You are actually way ahead of us in trying to do this! We don't have an officially documented API for commands such as searchEvents queries using the GraphQL Gateway.  

The system client documented [here](https://documentation.opencrvs.org/technology/interoperability/authentication-and-authorization):  is actually only allowed to do very restricted things at present such as respond to a Birth and Death registration webhook, or submit a birth or death notification from a health system, not perform actions such as searching all registrations, as that requires Civil registrar permission.  This JWT token doesnt have powerful enough scope. 
 You need the "registrar" scope.  Scope of all possible users is hard-coded in core [here](https://github.com/opencrvs/opencrvs-core/blob/5550f2454d8af080c0b4292de16735396ddaf83c/packages/user-mgnt/src/utils/userUtils.ts#L35
) - we do not advise that you fork Core to change this as you are introducing a security hole:   Essentially whenever you searchEvents, you are accessing personally identifiable information (PII) and that should be audited appropriately.

Our documentation should be updated to reflect what these system clients can currently do as of v1.0.1 and I will do that today.

So what can you do now?

As a quick hack, in "development", not "production", you could use a test Registrar's JWT that you obtain if using a registrars username and password and the test SMS code of 6 zeros.  Our data generator does that in order to populate a test environment with dummy registration data.  Example code is [here](https://github.com/opencrvs/opencrvs-farajaland/blob/521283aa4f8441d953867dbe99e7bd96483a4d7c/src/data-generator/index.ts#L118)

In "production", currently the only thing you can do is connect directly via [OpenHIM](http://openhim.org/docs/introduction/about) using a "mediator", as OpenHIM will audit anything that the system does, but this means that you can only use FHIR searching commands directly with our MongoDB FHIR database, not using ElasticSearch which is what the GraphQL Gateway can do. 

Our intention in the next major version of OpenCRVS is to add an optional JSON layer on top of GraphQL and audit system interactions with that layer in the OpenCRVS application GUI with the GraphQL queries fully documented.  We must track all interactions in the OpenCRVS GUI differentiating a system client from a registrar when using the GraphQL Gateway for any query or mutation that interacts with PII.

Could you possibly explain what it is you are trying to do with your interoperating system?  What is the business case that you are trying to solve?  If there is a strong argument for us to fast-forward a system client that has "registrar" JWT scope in order to use the full power of the GraphQL Gateway, we could discuss releasing that capability earlier in the next couple of months, before officially documenting the full API.

All the best,

Euan

**Comment by shukladhaval25** [comment]
The business case which we are trying to cover is fetch birth / death record and validate record with match information from CRVS system and make interoperability layer which can communicate with any SP (Special Protection) program. Like pension scheme or Child Education allowance. Our mediator should work over here to achieve such kind of requirement.

**Comment by euanmillar** [comment]
I think that you are describing 2 different business cases....

**1.** Could you explain "validate record with match information from CRVS system" in a bit more detail?  Is it correct to assume that this business case explains you piloting OpenCRVS alongside an existing system and you wish to validate what is captured in OpenCRVS for a birth or death **declaration** before it is **registered** by checking for duplicates in an existing system?

If so, we provide synchronous functionality out of the box ...  

If it will be a synchronous check, you can edit the function [here](https://github.com/opencrvs/opencrvs-farajaland/blob/521283aa4f8441d953867dbe99e7bd96483a4d7c/src/features/generate/handler.ts#L25) in the country repository to first connect and check with another system before the BRN is generated.   You can even override the BRN format entirely here.  This payload contains the full potential declaration bundle with all the data you need.

If it is an asynchronous check, and the response is not going to be immediate, then we can assist you with an undocumented solution in a minor release.  

You can add a [client-config](https://github.com/opencrvs/opencrvs-farajaland/blob/521283aa4f8441d953867dbe99e7bd96483a4d7c/src/client-configs/client-config.js#L12) / [client-config-prod](https://github.com/opencrvs/opencrvs-farajaland/blob/521283aa4f8441d953867dbe99e7bd96483a4d7c/src/client-configs/client-config.prod.js#L12) variable "EXTERNAL_VALIDATION_WORKQUEUE" as a **boolean** and set it to **true**:  so that the declaration goes into a "Waiting for validation" work queue.  The user knows that as far as the Civil Registrar is concerned the data passes manual checks, and we are just waiting for an external system to approve it.  You can manage that request in [this](https://github.com/opencrvs/opencrvs-farajaland/blob/521283aa4f8441d953867dbe99e7bd96483a4d7c/src/features/validate/handler.ts#L20) function with a webhook you can code. When it is successful you return the payload to the [CONFIRM_REGISTRATION_URL](https://github.com/opencrvs/opencrvs-farajaland/blob/521283aa4f8441d953867dbe99e7bd96483a4d7c/docker-compose.countryconfig.prod-deploy.yml#L28).  This then marks the registration as complete and moves it from the "Waiting for validation" work-queue into "Ready to print".  To take advantage of asynchronous external validation you need to configure the OpenHIM queuing channel to point to whatever endpoints you have coded for your webhook in the country config package.  If you need to set this up, please email [team@opencrvs.org](mailto:team@opencrvs.org?subject:OpenHIM) referencing this issue and we can schedule time to work with you on it.

**2.**  Regarding _"make interoperability layer which can communicate with any SP (Special Protection) program. Like pension scheme or Child Education allowance"_ surely this is something that you want to do after the registration is complete, validated either manually or externally and a birth registration number is created as only then do you know that it is complete and official.  To do this you should take advantage of our webhooks service.  Your system client should subscribe to the birth registration [webhook](https://documentation.opencrvs.org/technology/interoperability/webhooks).  Does it help to take a look at the [OpenCRVS > MOSIP](https://docs.mosip.io/1.2.0/integrations/mosip-opencrvs-integration) example?  After official birth registration, they create a National ID.  Why dont you do the same for registering with your Special Protection Program?

**Comment by shukladhaval25** [comment]
Let me share more details about that,

(1) 1. Could you explain "validate record with match information from CRVS system" in a bit more detail?
Validate Record means when any special protection program want to make sure data given by any individual is correct or not related to civil registration record. Eg. one person wants to register himself for any pension program then his given record should be verify first and based on that result that special projection program can process further. It may need to verify birth and death 
record and other civil registration.

2. Regarding "make interoperability layer which can communicate with any SP (Special Protection) program. Like pension scheme or Child Education allowance" :  We will review that and check.

**Comment by euanmillar** [comment]
Hi @shukladhaval25 thanks for the explanation, I misunderstood business process 1.  

Sounds like you need a specific search service that returns true or false if the registration exists based on the supplied information.  

The only thing you can do right now is follow the OpenHIM instructions to create a mediator for this task.  Use the FHIR API via OpenHIM.

In the meantime, we will discuss creating a new system client that has search capability to return the number of registrations that pass the search parameters.  We will see if we can include that in the next minor release.

The search parameters can be any name (likely to return multiple records), BRN or DRN, Tracking ID & contact mobile number used at the time of registration.

**Comment by euanmillar** [comment]
After consultation, if I understood correctly, it sounds like we need a SOCIAL_PROTECTION "scope" for a system client, who is a trusted government system.  This system can perform an advanced search using a JSON or GraphQL endpoint using a minimum number of parameters.  e.g.  event, locationId, childFirstName, childLastName, contactPhoneNumber, childsNationalId, deceasedsNationalID, mothersFirstName, fathersFirstName, informantsFirstName, informantsLastName, mothersNationalId, fathersNationalId, dateOfEvent (within maximum X months), dateOfRegistration (within maximum X months).  The search returns full records including PII and must therefore be audited accordingly.  While this can be retrieved using the FHIR API in OpenHIM, it requires multiple parameters.

**Comment by euanmillar** [comment]
This record search feature is going into immediate production. Watch this space! :-)

**Comment by SyedaAfrida** [comment]
This ticket do not require QA testing

**Comment by euanmillar** [comment]
@SyedaAfrida testing is complete using Postman and docs are ready.

@rajdeep21randhava @shukladhaval25 this is now fully tested and documented.  It will be in v1.2.0 stable release on Wednesday 25th Jan!  Thank you so much for requesting it.  

The documentation is now available [here](https://documentation.opencrvs.org/technology/interoperability/record-search-clients)
The Postman collections are available [here](https://github.com/opencrvs/opencrvs-farajaland/tree/develop/postman).

Sorry this took a long time, but we got inspired and built the API into the Advanced Search UI we had been planning so that non-technical staff could also search records in this way.
