### ISSUE TITLE
Provide placeOfBirth & placeOfDeath as multiple different values for birth & death certificate templates

### ISSUE THREAD

**Issue by rikukissa** [opencrvs/opencrvs-core#3861]
There's currently just one handlebar placeholder for a place of birth `{{ placeOfBirth }}`  and a place of death `{{ placeOfDeath }}`. 

<img width="708" alt="image" src="https://user-images.githubusercontent.com/1206987/187191939-4c90b38e-41fb-4470-96be-579caee03011.png">

With long places of birth, we'd like to have this information on multiple lines. What we propose is that in addition to current `placeOfBirth` placeholder, we'd have 

- placeOfBirthFacility
- placeOfBirthDistrict
- placeOfBirthState

- placeOfDeathFacility
- placeOfDeathDistrict
- placeOfDeathState

This would be a backwards-compatible change.

**Comment by euanmillar** [comment]
@tahmidrahman-dsi could you possibly do this?  In PDFUtils, we need to have the option to break apart placeOfBirth or placeofDeath so that, if placeOfBirthFacility, placeOfBirthDistrict and placeOfBirthState existed in the SVG, that they would be populated from data coming from placeOfBirth.  Please do the same for death.  @jpye-finch to test this, you would need to supply a birth and death cert with these handlebars on different lines.  Please liaise with Tahmid when he is building it.

**Comment by SyedaAfrida** [comment]
@anny320 this ticket is fixed and can be closed
[b cer.pdf](https://github.com/opencrvs/opencrvs-core/files/10081801/b.cer.pdf)
[d cer.pdf](https://github.com/opencrvs/opencrvs-core/files/10081802/d.cer.pdf)

**Comment by anny320** [comment]
completed
