### ISSUE TITLE
Configure certificate issuance

### ISSUE THREAD

**Issue by anny320** [opencrvs/opencrvs-core#3945]
https://www.notion.so/opencrvs/7d321101427640088c305b8bf630aa21?v=cd71becb0d0e4c14a13e67ba38fba1ac&p=0b021673c26943a2a8a955633b097281&pm=s

### Description
- configure how certificates can be issued in your country
- toggle on/off printing certificate in advance
- toggle on/off printing on collection??
- track issuance of a certificate (separate Epic?)

### Acceptance criteria

GIVEN
WHEN
THEN

### Design

(Link to Figma)

### Dev tasks

- [ ] Task 1

**Comment by jpye-finch** [comment]
@euanmillar @anny320 
I'm thinking this should be configurable for each event type. So not a sweeping configuration. Just to give us some flexibility. thoughts?

**Comment by euanmillar** [comment]
@jpye-finch I think we also need to look at collector form for this and do some research as "print in advanced" was designed for Bangladesh, and "certified copies" will also have a design impact in this case.  What happens legally to a document if it is printed in advance, but not actually handed over to the individual because they could not be found?  Also we need to consider the legal document number that is used in some countries.  How is that invalidated in this case?  I think that this one is more complicated than you may think as I have a lot of questions for @eduffus regarding it.  I think they should be designed together otherwise we will come back to make changes again and again.

**Comment by jpye-finch** [comment]
this has been built [Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBdnowIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--2d58337811ca80d67ef8307c785d415820d79193/image.png)
