### ISSUE TITLE
Incorrect error message showing for a new user when they go offline during 3 security questions setup confirmation

### ISSUE THREAD

**Issue by anny320** [opencrvs/opencrvs-core#4075]
**Describe the bug**
Error message needs updating to notify a user to check their connectivity

**To Reproduce**
Steps to reproduce the behaviour:
1. Create a new user as a national sys admin
2. Login using the new credentials and follow the prompts to create the new password and security questions.
3. When you get to the confirmation page, change your settings to go offline then click the confirm button.
4. See the error  "An error occurred, please try again"
5. Go online again and see the incorrect copy message " As you have connectivity, we can synchronise your declarations"
![image.png](https://images.zenhubusercontent.com/5e96badd8bea57051ce92eaf/40c7937e-a32a-45e6-8069-639238e25366)

**Expected behaviour**
GIVEN the user is offline 
WHEN they user click the Confirm button
THEN show a <Toast /> with the message "You are offline, please reconnect to complete your onboarding"

GIVEN the user is offline 
WHEN they reconnect
THEN show a <Toast /> with the message "You have reconnected"

Design with new styling (PR #4080)
-![image (23).png](https://images.zenhubusercontent.com/61d3cc06859638b515717606/9b968ffb-c9d5-4fdd-bc1f-637bf5ea3d83) 

![image.png](https://images.zenhubusercontent.com/5e96badd8bea57051ce92eaf/6cc533fc-a258-4adf-8b5d-46d7693f2e15)

**Screenshots**

**Desktop (please complete the following information):**
 
 - Browser chrome

**Smartphone (please complete the following information):**

**Additional context**

**Possible fixes**

(If you can, link to the line of code that might be responsible for the problem)

**Comment by jpye-finch** [comment]
@anny320 updated ticket to use acceptance criteria format to describe expected behaviour

**Comment by euanmillar** [comment]
@anny320 @jpye-finch this message you are seeing is actually a generic bit of code related to an entirely different process. We can discuss this if you like (workbox) This experience looks like it is being designed and addressed in https://github.com/opencrvs/opencrvs-core/issues/4211.  So in our view, this can be closed.

**Comment by jpye-finch** [comment]
I agree @euanmillar. 

Do we need a separate ticket to address the logic and copy of the declaration syncing toast?

**Comment by euanmillar** [comment]
@jpye-finch  I dont think we should have separate tickets for different requests, as this can only be a generic message because of how it is initiated.  The current copy is too specific to declarations, hence the misunderstanding.  It is triggered by Chrome through GraphQL's cache "Workbox".  GraphQL determines if there are any interrupted requests (which could be literally ANY request).  This happens in the Workbox code, external to our normal tracking in the Outbox.   It would be a lot of work to connect Workbox to Outbox and show a specific message.  I think that the cost of that effort outweighs the value of a specific piece of copy, and copy may have to be explicitly written for each request type if that design pattern was to be maintained.

**Comment by jpye-finch** [comment]
i don't think i am suggesting we do any linking of Workbox to outbox 

we have this ticket in backlog. https://app.zenhub.com/workspaces/opencrvs-core-5afeded64a54b06b54a969b2/issues/opencrvs/opencrvs-core/4211

To show Toast message when a user reconnects to the internet

**Comment by anny320** [comment]
closed
