### ISSUE TITLE
After QR code is scanned, Page timeout not occurring after 10 minutes

### ISSUE THREAD

**Issue by SyedaAfrida** [opencrvs/opencrvs-core#5006]
**Bug description:**
After QR code is scanned, Page timeout not occurring after 10 minutes

**Steps to reproduce:**
1. Click Ready to print> Print> print in advance
2. Scan QR code and observe for 10 mins

**Actual result:**
User stays logged in and Page timeout not occurring after 10 minutes

**Expected result:**
should show "You’ve been  timed out"

**Screenshot:**
![s1.png](https://images.zenhubusercontent.com/61920d086b30792f101fb9a3/897314df-df92-402c-b1a6-97fe0db47baf)![s2.jpg](https://images.zenhubusercontent.com/61920d086b30792f101fb9a3/33219cc5-5b2c-4cce-90ba-3748ad94fabf)

**Tested on:**
https://login.farajaland-qa.opencrvs.org/?lang=en

**Comment by Zangetsu101** [comment]
@SyedaAfrida Is this happening only for invalid certificates? In that case it shouldn't matter right?

**Comment by SyedaAfrida** [comment]
@Zangetsu101 This is happening for both valid and invalid cases

**Comment by Zangetsu101** [comment]
Alright then we need to take a look at what might be causing this

**Comment by Zangetsu101** [comment]
Another thing is this perhaps only happening in mobile devices? @SyedaAfrida

**Comment by SyedaAfrida** [comment]
Time out is working in web but not in mobile
![timeoy1](https://user-images.githubusercontent.com/94350336/230344720-2a35a3f9-007f-4ab0-86cd-a63d24cd7f09.png)

**Comment by Zangetsu101** [comment]
I'm guessing how you tested this was:

1. Scan a qrcode on your mobile
2. Leave the phone be
3. After 10 mins you unlock the app
4. You can see the certificate-verification screen again

The thing is, after 10 mins it would show "You been timed out" (which btw should be "You have been timeout out" instead) only if your screen stays awake the whole time. If your display goes to sleep, when you open the app again, the user sees UNLOCK PIN page so the timer gets reset and that is the expected behaviour

**Comment by SyedaAfrida** [comment]
@anny320 this ticket is fixed and can be closed
![timeoy1](https://user-images.githubusercontent.com/94350336/230344720-2a35a3f9-007f-4ab0-86cd-a63d24cd7f09.png)

**Comment by anny320** [comment]
completed
