### ISSUE TITLE
Dashboard: Completeness rates widget showing incorrect calculation for Completeness rates and Completeness rates by state widgets

### ISSUE THREAD

**Issue by anny320** [opencrvs/opencrvs-core#5376]
1. Login as National Sys Admin
2. Click Dashboard
3. Adjust the time period to current
4. Observe the completeness rate widget (you can also compare the calculation with the performance page to see the difference) Error- currently  showing  0

![Screenshot 2023-05-18 at 16.35.42.png](https://images.zenhubusercontent.com/61d3cc06859638b515717606/5bce6ef1-fc30-4c51-b069-247a258d173b)

Expected behaviour: Update the calculation to show the correct completeness data
for Completeness rates and Completenessrates by state widgets

**Comment by euanmillar** [comment]
@anny320 can we hold on this as I think @eduffus was telling me that it may be correctly displaying, its just not so intuitive about how you filter to get the value.  Also it may not be a priority right now if I understand Ed correctly?

**Comment by sadmananik** [comment]
While debugging I found out following issues,

1. When creating/updating populationEstimatesPerDay it counts one year from February to next February. It should count from January for a correct estimate calculation. 
2. There is no extension data for 2022 & 2023 years in the location. So that metabase can't be estimated correctly but in performance, it just uses the recent year's data.
3. On the performance page, If I select 2 individual years in the date filter then it just uses the one-year data instead of both of the years for estimation calculation. 
4. On the performance page, the end time in the date filter for the last 30 days and the last 12 months uses the last day of the current month instead of the current date.

**Comment by SyedaAfrida** [comment]
Bug:
Mismatch in Completeness rate and completeness rate by states. The total completeness rate is 42% but in each of the States it is 77%+
Filter used: previous 12 months not including this month.
![image (4)](https://github.com/opencrvs/opencrvs-core/assets/94350336/6dc62a20-cbf3-4f55-b8dc-35a43e9d7a46)

**Comment by Zangetsu101** [comment]
After generating data in production, it was noticed that the last month itself has around 1800 declaration which definitely seems like a bug. So first the data generator also needs to be fixed

**Comment by SyedaAfrida** [comment]
This ticket is fixed
![dashboard](https://github.com/opencrvs/opencrvs-core/assets/94350336/8012951d-a86a-4e9e-8118-218748237474)
