### ISSUE TITLE
Retrieve and assign a record at a status of "Ready for Review"

### ISSUE THREAD

**Issue by euanmillar** [opencrvs/opencrvs-core#5586]
**Description**

We need to make performance test that calls all the relevant GraphQL queries to download and assign a registration that contains 3 attachments

Refer to video:

![ready-for-review.gif](https://images.zenhubusercontent.com/5e96a2d4befb239e4f2bce95/86eaedc3-7c10-408b-b331-90be3bfacc63)

**Acceptance Criteria**

User type: Registrar

Transaction time within 30 seconds

Concurrent requests up to 3 requests/sec

Total attachements = 3 (each original image size of 4MB - each image should compress to 0.4MB)

10 lines in the record history table

Network must be throttled to mimic 3G connectivity: 3 Mbps when running the test

**Dev Tasks**

- [ ] Pass a flag to data-generator for performance testing purposes, so that when creating performance test data, each declaration that is made uploads 3 x 0.4MB attachments using a library or API that can generate images.
- [ ] Edit data generator so that in addition to the existing data, there are 1500 such declarations in a ready for review state in the country.  Each declaration must have at least 10 history items available in the workqueue by repeatedly calling the fetchViewRecordByComposition 10 times after each declaration has been processed.  The data generator must export all FHIR ids for these declarations to a text file so that the performance test can fetch them when calling fetchBirthRegistrationForReview
- [ ] Write a "ready-for-review" performance test in https://github.com/opencrvs/performance-tests that calls the fetchBirthRegistrationForReview API, looping through the available FHIR IDs. The test will be run like this:

40 birth declarations per minute. Ran for 2 minutes.
60 birth declarations per minute. Ran for 2 minutes.
100 birth declarations per minute. Ran for 2 minutes.
150 birth declarations per minute. Ran for 2 minutes.
200 birth declarations per minute. Ran for 4 minutes.

When the last FHIR ID is searched the test should end

**Comment by rikukissa** [comment]
Test case & initial analysis on the results can be found here: 
https://github.com/opencrvs/performance-tests/tree/master/scenarios/1500-records-in-database#retrieve-ready-for-review-record-with-an-id

After setting up the repository, you can run the test with 
```
yarn run-scenario 1500-records-in-database/retrieve-ready-for-review-record-with-id
```

### Differences between requirements and implementation

As for the overall approach, I started by ruling out us much of the test scope as I could, mostly in terms of variables that might affect test results such as network speed and deployment flee size. I did this to get us to as reproducible and easy-to-interpret "raw" values as we can. These values do not directly answer to "how many simultaneous users can OpenCRVS support?" but as long as our endpoints as performant, the answer should be "there's no limit".

Once we know how long it takes for the server to process a single request and the request and response payload sizes, we can derive how long it takes to complete the full process with any connection speed, deployment size and simultaneous users. It's also easier to compare results between OpenCRVS versions and you can run the tests quickly in a local environment which enables us to quickly load in different datasets.

> Transaction time within 30 seconds

As the value I'm measuring in these tests is the time the server takes to process the request, I lowered this limit to be 5 seconds to start with. A sensible limit for this would be `<1s` as it's a local database read. 

> Concurrent requests up to 3 requests/sec

The tests currently make sequential requests. Again, there are so many variables in play when creating concurrent requests (deployment size, number of CPUs, number of MongoDB instances, number of service instances, timeout limits) that for the test results wouldn't serve the purpose of tracking and improving performance.

Concurrent requests could be used to answer "how many concurrent requests can OpenCRVS stand before failures?" but improvements in those results would be a side effect of us being able to make processing times shorter.

> 10 lines in the record history table

Increase in download times and payload sizes is tested by [Increasing audit history size](https://github.com/opencrvs/performance-tests/tree/master/scenarios/fresh-installation#increasing-audit-history-size) test case.

> Network must be throttled to mimic 3G connectivity: 3 Mbps when running the test

We can use the `data_sent` and `data_received` metrics to calculate the exact time it takes for different connection types to process the request. 

```
data_sent / upload_speed + data_received / download_speed + time_processing
```

Dev Tasks

 Pass a flag to data-generator for performance testing purposes, so that when creating performance test data, each declaration that is made uploads 3 x 0.4MB attachments using a library or API that can generate images.
 Edit data generator so that in addition to the existing data, there are 1500 such declarations in a ready for review state in the country. Each declaration must have at least 10 history items available in the workqueue by repeatedly calling the fetchViewRecordByComposition 10 times after each declaration has been processed. The data generator must export all FHIR ids for these declarations to a text file so that the performance test can fetch them when calling fetchBirthRegistrationForReview
 Write a "ready-for-review" performance test in https://github.com/opencrvs/performance-tests that calls the fetchBirthRegistrationForReview API, looping through the available FHIR IDs. The test will be run like this:
40 birth declarations per minute. Ran for 2 minutes.
60 birth declarations per minute. Ran for 2 minutes.
100 birth declarations per minute. Ran for 2 minutes.
150 birth declarations per minute. Ran for 2 minutes.
200 birth declarations per minute. Ran for 4 minutes.

When the last FHIR ID is searched the test should end
