### ISSUE TITLE
Marriage: Performance analytics view

### ISSUE THREAD

**Issue by jpye-finch** [opencrvs/opencrvs-core#6034]
### Description

- Adds performance management view for marriages
- Same as birth and death without Completeness rates sections at all admin levels

Performance sections:
- Reg rates 
- Certifications 
- Source of reg
-  Corrections 
- Fees 
- Status
- Reg by status

### Acceptance criteria

GIVEN I am a Registrar
WHEN on the Performance page and I select Marriages
THEN loads the marriage data for my selected Administrative Area

### Design
https://www.figma.com/file/O6PevbBv0lApmXWYotR8sf/OpenCRVS-Design-Specifications-v2?type=design&node-id=17590%3A128657&mode=design&t=iksunCP8jqOh4nOA-1

### Dev tasks

- [ ] Task 1

**Comment by eduffus** [comment]
@jpye-finch we need to add a section here (or another ticket) to capture the fact that we need marriage data available within the dashboards also.

**Comment by euanmillar** [comment]
@jpye-finch @eduffus  I have initial 4 points to make:

1. The View link for registrations on births and deaths goes to a subsequent page containing birth specific info like so:

![Image](https://github.com/opencrvs/opencrvs-core/assets/3169954/716651c6-8712-4f16-a387-fb4ccfc6be92)

So I think that saying "Same as birth and death without Completeness rates sections at all admin levels" isnt enough of a guide to QA.

2. Registrations totals also contain gender disaggregation for births and deaths which isnt necessary for death. I notice they are gone from the marriage design so that should be an acceptance criteria re point 1

3. Dashboards is an entirely different section with an entirely different design and build process (custom code vs Metabase) @eduffus so we need new tickets for estimation for that.  Estimation of that will take time to understand.

4. In the Marriage application settings story, you mentioned delayed fees for marriage reg.  Is that ticket wrong or is this design wrong as those fees are not displayed in this design
