### ISSUE TITLE
Refactor ListViewSimplified on the Review page to use ListReview

### ISSUE THREAD

**Issue by jpye-finch** [opencrvs/opencrvs-core#6039]
ListViewSimplified has been split into different list components and deprecated

This ticket creates ListReview 

This ticket is to use ListReview on the declaration review.

Other instances of ListViewSimplified remain and will be updated accordingly

## Dev task
- [x] Fix conflicts & see why tests are failing

**Comment by euanmillar** [comment]
@jpye-finch  you said in the description that "ListViewSimplified has been split into different list components and deprecated".

I checked out the changes you made in that PR and there are still many instances of ListViewSimplified still in use in that PR.  

A developer is required to do more than just fix the tests as the tests are failing because there might be UI requirements that are broken in other areas because of the changes made in this PR just in one case.  The logs are expired and no longer available so I dont know for sure.  The PR is very stale and needs to be applied again to a new PR from the develop branch release v1.3 as sections like CustomFieldTools that use this component no longer exist.

There are a host of components that use the ListViewSimplified and all need refactored if this is to be deprecated, such as:  AdministrativeLevels.tsx, SettingsPage.tsx, Application.tsx (Application settings), BirthDelayedFee, Workqueue tabs etc etc.

The description says: "ListReview needs to be applied to:

Declaration review page
User form creation
Performance management page"

But what about all the other cases?

**Comment by jpye-finch** [comment]
Have updated description

**Comment by naftis** [comment]
@SyedaAfrida The review page component has gone through refactor in all review sections (birth, death, marriage) and view record. This needs to be reviewed for regression when deployed to QA

**Comment by SyedaAfrida** [comment]
**Bug:** Alignment not correct in Change all and upload link in review page


https://github.com/opencrvs/opencrvs-core/assets/94350336/583a38ca-c50d-4ac5-a5a9-f45868b37f10

**Comment by SyedaAfrida** [comment]
This ticket is fixed


![Image](https://github.com/opencrvs/opencrvs-core/assets/94350336/5438be21-bd0f-410f-bc63-21d732bb25ca)
![Image](https://github.com/opencrvs/opencrvs-core/assets/94350336/314b553f-5e4e-48e2-be3c-c3c8b3546594)
