### ISSUE TITLE
Change copy from "Send notification" to "Register event" when Registering any declaration

### ISSUE THREAD

**Issue by SyedaAfrida** [opencrvs/opencrvs-core#6154]
**Bug description:**
Change copy from "Send notification" to "Register event" when Registering any declaration

**Steps to reproduce:**
1. Login to Registrar
2. Declare any event
3. Observe review page

**Actual result:**
Showing "Send notification" 
**Expected result:**
Change copy from "Send notification" to "Register event" when Registering any declaration

**Screenshot:**
![image (8)](https://github.com/opencrvs/opencrvs-core/assets/94350336/e651dfe2-31b5-40b0-94c0-03f64ef99cd9)

**Tested on:**
https://login.niue.opencrvs.org/?lang=en

**Comment by euanmillar** [comment]
@SyedaAfrida @jpye-finch @eduffus @anninawersun  it appears that in Farajaland, the same content key "Declaration complete" or "Declaration incomplete" was used for field agents, registration agents and registrars in this location.  In Niue the desire is for this heading to be different for each user, because Field Agents must see "Send notification".  Therefore I am opening a core PR so that these keys can be unique. For Field Agents for Farajaland it will say "Declaration complete" or "Declaration incomplete", for registration agents it will say "Send for approval" and for Registrars it will say "Register event"

**Comment by euanmillar** [comment]
https://github.com/opencrvs/opencrvs-core/pull/6159

**Comment by SyedaAfrida** [comment]
Fixed in Niue. But not deployed in Farajaland core yet. Need to test in core.
![reg](https://github.com/opencrvs/opencrvs-core/assets/94350336/22d1dab8-06bf-4619-8883-8e12846573a4)

**Comment by SyedaAfrida** [comment]
This bug is fixed
![register](https://github.com/opencrvs/opencrvs-core/assets/94350336/596f1028-18d1-4063-8d2b-5adf71d05b7e)
