### ISSUE TITLE
 French translation improvements

### ISSUE THREAD

**Issue by SyedaAfrida** [opencrvs/opencrvs-core#6458]
Need to change approach for missing french translation in application

**Comment by tahmidrahman-dsi** [comment]
@eduffus some keys are later added and not in the list, I have added those keys in the list and colored the rows as red as those need to be reviewed. Could you please have a look?

**Comment by eduffus** [comment]
I have now reviewed all the translations and made a number of updates.

**Comment by euanmillar** [comment]
@eduffus when you say you made a number of updates, then the status on this should have changed back to ready to build so that a developer picked them up and applied the changes.  Doing that now.  I am moving this ticket to 1.6.0. @tahmidrahman-dsi can you apply these changes to your current Madagascar copy please and then open a PR in countryconfig & farajaland.  It shouldnt affect the 1.5.0 release as these are all configurable lines of copy.

**Comment by tahmidrahman-dsi** [comment]
@euanmillar, I think I can apply these changes in Madagascar csv. However, I am thinking to update the csv as such that it will have all the keys of this doc and their English, French, Malagasy messages. There can be several message keys for which they don't have their translations, for those I will use messages from this doc. In that case we can export it in a sheet and ask them review.

**Comment by euanmillar** [comment]
Developer needs to manually pick the French content changes in red in this [file](https://docs.google.com/spreadsheets/d/1-1Ktx--eoVdVm-uIpXYq-oDtf1E9bJGm/edit?gid=134322559#gid=134322559) into client.csv.  We cant just export this and prelace because there are new content keys in 1.5.0.

Once this is done, the source file Excel needs to be updated with the latest content for future amends

**Comment by euanmillar** [comment]
Working on a new translation doc for 1.5.0 and will mark new keys required for review.

**Comment by euanmillar** [comment]
Blocked awaiting discussion: https://opencrvsworkspace.slack.com/archives/GHCFF9M6X/p1727358464480959

**Comment by euanmillar** [comment]
Closing awaiting a new approach
