### ISSUE TITLE
System crash when try to print a declaration which was previously incomplete and assigned to RA

### ISSUE THREAD

**Issue by SyedaAfrida** [opencrvs/opencrvs-core#6492]
**Bug description:**
System crash when try to print a declaration which was previously incomplete and assigned to him

**Steps to reproduce:**
1. Login to RA
2. . Download> assign any incomplete declaration 
3. Logout
4. Login to registrar
5. Unassign RA from the record
6. Complete the declaration and register
7. Assign the record from ready to print
8. Login to RA
9. Go to ready to print
10. Try to print that record

**Actual result:**
System crash occurs when RA try to print

**Expected result:**
RA should become automatically unassigned from the record as they were unassigned and the status is changed by the registrar

**_Note:_** This bug is only not appearing for Registered status or incomplete declaration. This can appear for any status or complete declaration also. But in that case there wont be system crash. For this reason the best approach would be whenever the status is changed for any declaration by registrar, RA should be automatically un assign from that record.

**Screen recording:**

https://github.com/opencrvs/opencrvs-core/assets/94350336/6dd2f651-362e-40f6-bfd1-45d795e14541

for complete declaration
https://www.loom.com/share/6df8dff3b9cb4cab96a323fcaf206162?sid=565cad86-17bb-4a42-8f4b-295a13e33f32

**Environment:**
https://login.farajaland-staging.opencrvs.org/?lang=en
https://login.farajaland-qa.opencrvs.org/?lang=en

**Version:**
 V1.3.3, V1.4.0,

**Comment by eduffus** [comment]
@SyedaAfrida Can you confirm that this only happens if the record was submitted part-complete?
What about if the record was submitted complete then follow the same flow. Does that work fine?
A bit of extra testing around the "assign" functionality would be good here e.g. cases where RA users were last assigned at logout and the status of the record gets moved on by a Registrar, then the RA logs back in and accesses the record...
@SyedaAfrida let me know if this makes sense.

**Comment by SyedaAfrida** [comment]
@eduffus  Incase the record was submitted complete, then we follow the same flow- There is no system crash. But there missing field related bugs. I will create a separate ticket for that bug

**Comment by SyedaAfrida** [comment]
@eduffus  I have gone through the assigned functionalities. Though there wont be system crash for complete declaration, but there are other bugs appearing like missing data in certificate and record audit. For this reason the best approach would be whenever the status is changed for any declaration by registrar, RA should be automatically unassign from that record and a toast for unassigned by registrar should appear when logged in. I have mentioned this in the ticket to avoid confusion

**Comment by naftis** [comment]
There are 2 things to consider here, given that you have downloaded the record as `f.katongo` but after that `k.mweene` has assigned the record to himself:
- the DownloadButton in the work queue which shows the avatar shows that you've downloaded the record instead of the correct assignment. Should it show the actual assignment when available?
- if you have downloaded the record, you can open it by clicking it and seeing all the downloaded information. If you have network connectivity, should there be a check to see the up-to-date assignment before seeing the downloaded information?

Toasting the user as Syeda suggested can be done: when updating work queues, check that if you have downloaded records that aren't assigned to you, and toast the user and clear the downloaded record.

I'd suggest creating the toast as a separate feature unrelated to this ticket.

**Comment by SyedaAfrida** [comment]
This bug is not properly fixed

1.  when try to assign multiple declaration at a time before older one is properly assigned than downloading is not completed and shows error

https://github.com/opencrvs/opencrvs-core/assets/94350336/9119a2ff-b50a-4a5b-984a-9a89eb62a428


2. when a record is reinstated by themselves then shows unassigned toast and tracking id appears twice


![Image](https://github.com/opencrvs/opencrvs-core/assets/94350336/29f31eaa-3542-402e-84c5-de3b10eed324)

**Comment by euanmillar** [comment]
@Zangetsu101 @naftis @Nil20 I think that this is quite a regression so I'm going to revert this fix so it can be resolved in 1.3.4 / 1.4.2. @rikukissa lets try to get the next hotfix release out asap to resolve this issue.

**Comment by euanmillar** [comment]
@SyedaAfrida I tried to reproduce what you faced here but it works fine for me.  Weird.

**Comment by SyedaAfrida** [comment]
This bug is not fixed yet
When try to assign multiple declaration at a time before older one is properly assigned than downloading is not completed and shows error

![Image](https://github.com/opencrvs/opencrvs-core/assets/94350336/8c99c091-3f81-44dc-ac46-62382b540c69)

**Comment by SyedaAfrida** [comment]
This bug is fixed


https://github.com/opencrvs/opencrvs-core/assets/94350336/a3a154a9-9179-483c-bb2e-fe6c09b86f87
