### ISSUE TITLE
waiting on port 3040. waiting on auth microservices

### ISSUE THREAD

**Issue by abubaker909** [opencrvs/opencrvs-core#6521]
I am installing opencrvs.  My script is getting stuck on auth microservices. It is giving 

CFVs/components: $

concurrently 'storybook

dev-ci quiet -p 6060

''tsc - w'

Killed
 
how to solve this issue i dont know how to solve this issue. Any help?

**Comment by naftis** [comment]
There can potentially already be something running in your port 6060 or the Storybook isn't able to start due to an memory issue for example. If you need further help with this, please let us know:
* which branches are you running of core & country config
* which Node version you are using
* which system you are running OpenCRVS on.

I'm closing this for now.
