### ISSUE TITLE
Handlebar for the details of the user who is certifying the declaration

### ISSUE THREAD

**Issue by Zangetsu101** [opencrvs/opencrvs-core#6529]
The details of the user who is certifying the declaration needs to be exposed via a handlebar as the one certifying could be the Registrar who registered the declaration or the RegistrationAgent who verified it or it could even be some other user from a different office.

**Comment by tiri39** [comment]
Tested on Uganda env (https://register.uganda.opencrvs.org/) , not on core.

Found one issue - **While printing certificates, the logged in user (who is certifying the record) details is not shown.**

When an user tries to print a declaration that was registered by another user, the certificate shows the details of the user who registered the certificate, instead of the one who is printing the certificate.

**Steps to reproduce -**

1. Login as RA/registrar.
2. Navigate to ready to print workqueue.
3. Print any declaration that was registered by another user.
4. Observe the user details on the certificate preview page.

**Recording -**

https://github.com/user-attachments/assets/42ebec28-da22-4c29-bed8-f868b16ca76c

**Comment by Zangetsu101** [comment]
@tiri39 I'll be closing this one as completed as the details of the loggedInUser are indeed available to be used in the certificate. Now as for which user's details to show on the certificate (the one who registered or the one who's printing the certificate) is a configuration issue and we'll need further discussion on this.
