### ISSUE TITLE
Investigate potentially buggy translation code when assumed first language is 'en'

### ISSUE THREAD

**Issue by naftis** [opencrvs/opencrvs-core#6938]
The problem with the below code affects naming of offices & health facilities

https://github.com/opencrvs/opencrvs-core/blob/5c402eabc5956ce0c74064fa4f2f4143065670ab/packages/workflow/src/features/registration/fhir/fhir-utils.ts#L116
https://github.com/opencrvs/opencrvs-core/blob/fd17748db973101b849b0002722d157e318f459d/packages/notification/src/features/inProgress/handler.ts#L91
https://github.com/opencrvs/opencrvs-core/blob/f62ba4180ba65f474455be8dab059059432767cb/packages/notification/src/features/utils.ts#L140

If the default language isn't 'en', would this code work?

**Comment by naftis** [comment]
If the default language is not English like in Ethiopia & Burkina Faso(?) we need to look into this technical debt

**Comment by Zangetsu101** [comment]
Let's use an environment variable to define the languages e.g. "en,fr" and we can use the first one as the default

**Comment by tareq89** [comment]
I have searched the entire codebase of the `develop` branch for the keyword `(language === 'en')` and found only two occurrences in the updated codebase:

```
2 results - 2 files

packages/client/src/utils/draftUtils.ts:
  65    }
  66:   if (language === 'en') {
  67      return getEngName(sectionData, lastNameFirst)

packages/notification/src/features/utils.ts:
  134    return (
  135:     (language === 'en'
  136        ? location.name
```

**Analysis:**

1. **Client Package:**
   In the `client` package, the code compares the currently selected locale with `en`. If the language is English, it calls a dedicated method for English. Otherwise, it falls back to the default method.

2. **Notification Package:**
   In the `notification` package, the `language` variable is obtained from `getDefaultLanguage()`. If the default language is English, it returns `location.name`. If the default language is not English, it returns `location.alias`.

**Potential Issue:**

If the configuration includes `fr,de` (French and German), the default language would be French. However, the current logic will return `location.alias`, which is the German translation. This is because the comparison is only checking against `en`.

**Proposed Solution:**

We need to **refactor this comparison**. Currently, there is **no way to inform the notification service** about the desired language for notifications. For now, we should **always return the default language value** (`location.name`).

**Future Consideration:**

Ideally, the system should have a **mechanism to specify the language for notifications**, which is currently missing. We should have a separate tech discussion on this one. cc: @rikukissa 

@naftis , can you review my observation?

> Let's use an environment variable to define the languages e.g. "en,fr" and we can use the first one as the default

@Zangetsu101 , already they are configured via `process.env.LANGUAGES` in `dev.sh`, `docker-compose.ci.yml`, whose value is initialised as `en,fr`

**Comment by Zangetsu101** [comment]
Completed in #7361
