### ISSUE TITLE
Create regression test suites for death section

### ISSUE THREAD

**Issue by jamil314** [opencrvs/opencrvs-core#7063]
### Dev tasks

- [x] Death test case 1, 8 
- [x] Death declaration 1 - 10

**Comment by SyedaAfrida** [comment]
1. Few testcase  skipped like adding supporting document in  declaration 2,4 , adding comments in testcase  8
2. Review page UI not properly showing like birth

![Image](https://github.com/user-attachments/assets/817a3042-cf77-46dd-b2cf-2aad990aaed6)


3. Make testcase  9 where informant type in other than spouse, then from review page click change and update each field except informant type. Currently in testcase 8, since informant is spouse, no update functionality was tested for informant details page. Also make date of death before 45 days to test reason for late registration

**Comment by SyedaAfrida** [comment]
fixed
