### ISSUE TITLE
In correction request block for death declaration, Supporting document's names are not showing and when requester in someone else- relationship to deceased is not showing

### ISSUE THREAD

**Issue by SyedaAfrida** [opencrvs/opencrvs-core#7074]
**Bug description:**
- In correction request block for death declaration, Supporting document's names are not showing 
- when requester in someone else- relationship to deceased is not showing

**Steps to reproduce:**
1. Login as RA
2. Go to Ready to Print
3. Correct any death record 
4. Select requester as someone else> Put relationship to deceased
5. Add multiple supporting documents 
6. request for correction
7. Logout
8. Login as Registrar
9. Go to Ready for review
10. Download> Assign> Review that record
11. Observe correction request block

**Actual result:**
-  Supporting document's names are not showing 
- Undefined  is showing in place of relationship to deceased 

**Expected result:**
- should show Supporting document's names
- should show Someone else- relationship to deceased 

**Screenshot:**

https://github.com/opencrvs/opencrvs-core/assets/94350336/12af9abc-a8f1-4f04-ab49-e21c10db02a8

![death undefined](https://github.com/opencrvs/opencrvs-core/assets/94350336/d25eda1d-3b05-4c44-969a-535416ca1b2a)

**Tested on:**
https://login.farajaland-qa.opencrvs.org/?lang=en

**Comment by Zangetsu101** [comment]
@tareq89 Was the supporting documents issue solved?

**Comment by Zangetsu101** [comment]
Apparently the supporting document name shows up after you unassign and then assign the declaration again

**Comment by tareq89** [comment]
> Apparently the supporting document name shows up after you unassign and then assign the declaration again

Since this ticket is partially solved, I have created another [bug issue](https://github.com/opencrvs/opencrvs-core/issues/7261) in favor of unsolved one and moving this ticket to QA testing.

**Comment by tareq89** [comment]
@SyedaAfrida, @tiri39 , requesterOther issue has been solved in this issue's pull request.

**Comment by tareq89** [comment]
This is a critical issue.

When a correction request is made, it triggers the file [requestCorrectionRoute](https://github.com/opencrvs/opencrvs-core/blob/fc2594d8e414816f41e00951fb06bb17af2b281a/packages/workflow/src/records/handler/correction/request.ts) , which updates the request in the Hearth bundle.

When a reviewer assigns this request to themselves from the review section, the request triggers the [downloadRecordHandler](https://github.com/opencrvs/opencrvs-core/blob/ac35fd2a2e5226cbfde04cd0f97bc94e41cef6f2/packages/workflow/src/records/handler/download.ts). 

This file first fetches the Hearth bundle using a MongoDB aggregation pipeline defined in [getRecordByIdHandler](https://github.com/opencrvs/opencrvs-core/blob/d70400bec77c17eb90838f6f74228f7d27e3c79a/packages/search/src/features/records/handler.ts). 

In the resulting bundle, there is no DocumentReference entry, and this bundle is sent to the browser.

In the next tick, a modified bundle is updated and saved in Hearth.

In the browser, the reviewer sees a review declaration without the supporting `DocumentReference` for the correction request. If the user unassigns and reassigns the request to themselves, they then see the correction supporting document.

I have tried running the aggregation pipeline in mongodb compass right after a correction request is made and someone assigns himself that request. In first case, the pipe output does not contain DocumentReference, but in the second, it does.

My strong guess is that something changes in the bundle during the next tick update, which is why the DocumentReference appears in subsequent requests.

**Comment by SyedaAfrida** [comment]
This ticket is fixed


https://github.com/opencrvs/opencrvs-core/assets/94350336/21ed5308-af07-4e8c-b64f-e72a93cd03ae
