### ISSUE TITLE
Wrong status shown in the Comparison View Page of duplicate record.

### ISSUE THREAD

**Issue by tiri39** [opencrvs/opencrvs-core#7439]
**Bug description:**
When a duplicated record is 'marked as duplicate', its status becomes 'archived'. Then if we reinstate the record, the status becomes  'In review'. But it shows 'archived' in the comparison view page.

**Steps to reproduce:**
1. Login as RA / registrar.
2. Navigate to the 'Ready for Review' workqueue.
3. Navigate to the Review page of a duplicate record and mark it as a duplicate.
4. Search the record by tracking id and Reinstate it.
5. Navigate to the review page of the reinstated record.
6. Select any tracking id to see the comparison view.
7. In the comparison view page, observe the status of the duplicate record.

**Actual result:**
The status is 'archived'

**Expected result:**
The status should be 'In review'.

**Screen recording:**

https://github.com/user-attachments/assets/f008143a-cf21-4b08-8fef-98e34547a2a2

**Tested on:**
https://login.farajaland-qa.opencrvs.org/?lang=en

**Version:**
v1.6.0

**Comment by Siyasanga** [comment]
@tiri39 It looks like the actual status was supposed to be the last one that was set e.g `Declared` for the example above instead of `In review`. It looks like we don't have that status as an option for `RegistrationStatus` e.g here is a list of posible declaration status that I [found in code](https://github.com/opencrvs/opencrvs-core/blob/42a4018785054bb4e6842948ad998b9fd36cf3fc/packages/client/src/utils/gateway.ts#L1953-L1965)
```
export enum RegStatus {
  Archived = 'ARCHIVED',
  Certified = 'CERTIFIED',
  CorrectionRequested = 'CORRECTION_REQUESTED',
  DeclarationUpdated = 'DECLARATION_UPDATED',
  Declared = 'DECLARED',
  InProgress = 'IN_PROGRESS',
  Issued = 'ISSUED',
  Registered = 'REGISTERED',
  Rejected = 'REJECTED',
  Validated = 'VALIDATED',
  WaitingValidation = 'WAITING_VALIDATION'
}
```

**Comment by SyedaAfrida** [comment]
This ticket is fixed

https://github.com/user-attachments/assets/ff9474bf-a4a2-4e7f-b0b1-302cb5ece1be
