### ISSUE TITLE
In advance search, cannot find correct result when record of in progress & in review are searched when event location is  health institution

### ISSUE THREAD

**Issue by SyedaAfrida** [opencrvs/opencrvs-core#7494]
**Bug description:**
In advance search, cannot find correct result when record of in progress & in review are searched when event location is  health institution.

**Steps to reproduce:**
1. Login as RA/ Local registrar/ National registrar
2. Have some records in in progress and ready for review when event location is health institution
3. Open advance search
4. Go to birth/ death tab
5. In status of record keep Any status/ in progress/ in review
6. In event details Select health institution and enter the name
7. Click search
8. Observe the result

**Actual result:**
Desired records are not shown

**Expected result:**
Should show expected records

**Screenshot/ Recording:**

https://github.com/user-attachments/assets/7dfbc296-3245-4361-a13d-2ae9483539e0

**Tested on:**
https://login.farajaland-qa.opencrvs.org/?lang=en

**Version:**
V1.6.0

**Comment by SyedaAfrida** [comment]
This bug is not fixed

https://github.com/user-attachments/assets/86d91b29-a809-46b6-8793-11de5ccd6471

**Comment by Siyasanga** [comment]
Thanks for the feedback @SyedaAfrida, just a question regarding the records being searched, did you create new ones after the the fix was deployed? Because the old declaration will still not be "findable"

Reason being, the main issue was caused by a dscriptency in how we were saving a new `declaration` that has a health institution as a `place of birth`. Since we already have data about the institutions when a health institution is selected as e.g `place of birth` we only sent a `reference`/`id` of the institution and `fhir` is be able to link the all the institution's data for the `declaration` on `Mongo`(the main database) but the ElasticSearch(a database we use for searching) logic was dependent on the whole `location` data being present in the in the `declaration` being saved and because we were not sending location details to ElasticSearch it means they were saved without `location` as a result we can't find them by `location`

**Comment by Zangetsu101** [comment]
Thanks @Siyasanga for the explanation. @SyedaAfrida as Siya mentioned, could you check if the bug is reproducible with newly created declarations? As for older declarations, if the declarations were created prior to v1.5.0, then they should be searchable but those that were created in v1.5.0 will be the problematic one.

Our recommendation would be to upgrade to v1.6.0 as this was fixed there.

**Comment by SyedaAfrida** [comment]
@Zangetsu101 @Siyasanga All the declaration are newly created

**Comment by SyedaAfrida** [comment]
This bug is fixed

https://github.com/user-attachments/assets/91b22e69-6ad8-4aee-9f2f-9b6bcdf1c955

**Comment by SyedaAfrida** [comment]
This bug is fixed

https://github.com/user-attachments/assets/5788cbea-1afa-45ad-bb75-65e8ccb7156b
